// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZMnjuJ2_UUDi53sB6O0fljO7au3Ov6dU',
    appId: '1:693968989868:web:220ad0521796613e133909',
    messagingSenderId: '693968989868',
    projectId: 'galleryapp-df005',
    authDomain: 'galleryapp-df005.firebaseapp.com',
    storageBucket: 'galleryapp-df005.appspot.com',
    measurementId: 'G-KXM2FNEZ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwj3PYnzZMrK4SfygyS6O-8sW8IUlKEs',
    appId: '1:693968989868:android:706dc5b05c4d76f5133909',
    messagingSenderId: '693968989868',
    projectId: 'galleryapp-df005',
    storageBucket: 'galleryapp-df005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA89kZ_0VxgAAWIOi45UnLnRTJvZbowOeQ',
    appId: '1:693968989868:ios:1bab9911c224df25133909',
    messagingSenderId: '693968989868',
    projectId: 'galleryapp-df005',
    storageBucket: 'galleryapp-df005.appspot.com',
    iosBundleId: 'com.example.firebaseImageStorage',
  );
}
